"""add unique ruleset name

Revision ID: be797480072f
Revises: 54e647d21265
Create Date: 2026-06-05 22:18:42.546878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'be797480072f'
down_revision: Union[str, Sequence[str], None] = '54e647d21265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_rulesets_name', 'rulesets', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_rulesets_name', 'rulesets', type_='unique')
    # ### end Alembic commands ###
