"""use bigint for discord user id

Revision ID: da5c114ea009
Revises: be797480072f
Create Date: 2026-06-05 22:21:44.362857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'da5c114ea009'
down_revision: Union[str, Sequence[str], None] = 'be797480072f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'discord_user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'discord_user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
